version: '3.8'
services:
  postgres:
    image: 'postgres:14.8-alpine3.18'
    environment:
      POSTGRES_DB: drones-administration-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "41375:5432"
  drones-administration-service:
    container_name: drones-administration-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    image: drones-administration-service:latest
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres/drones-administration-db
      DB_USER_NAME: postgres
      DB_PASSWORD: postgres
      DRONES_SCHEDULER_NAME: drones-scheduler-task
      DRONES_SCHEDULER_POOL_SIZE: 10
      DRONES_SCHEDULER_TASK_DELAY_IN_MS: 30000

