--liquibase formatted sql
--changeset bishoy:1
CREATE TABLE IF NOT EXISTS MEDICATION
(
    CODE           VARCHAR(100) PRIMARY KEY,
    NAME           VARCHAR(255),
    WEIGHT_IN_GRAM INTEGER,
    IMAGE_URL      TEXT,
    CREATED_DATE   TIMESTAMP,
    MODIFIED_DATE  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DRONE
(
    SERIAL_NUMBER                  VARCHAR(100) PRIMARY KEY,
    LOAD_WEIGHT_LIMIT_IN_GRAM      INTEGER,
    BATTERY_CAPACITY_IN_PERCENTAGE INTEGER,
    MODEL                          VARCHAR(255),
    STATE                          VARCHAR(255),
    CREATED_DATE                   TIMESTAMP,
    MODIFIED_DATE                  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DRONE_MEDICATION
(
    DRONE_SERIAL_NUMBER VARCHAR
        CONSTRAINT DRONE_MEDICATION_DRONE_SERIAL_NUMBER_FK
            REFERENCES DRONE,
    MEDICATION_CODE     VARCHAR
        CONSTRAINT DRONE_MEDICATION_MEDICATION_CODE_FK
            REFERENCES MEDICATION
);